on:
  push:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pycabbage/workflow-call-test/.github/workflows/workflow1.yml@main
        with:
          input_name: 'Sample'
