on:
  workflow_call:
    inputs:
      input_name:
        required: true
        type: string
    outputs:
      result:
        description: ""
        value: ${{ jobs.apply.outputs.name }}

jobs:
  apply_ecr:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Apply ECR"
  build_container:
    runs-on: ubuntu-latest
    needs: apply_ecr
    steps:
      - run: echo "Build container"
  apply:
    runs-on: ubuntu-latest
    needs: build_container
    outputs:
      name: ${{ steps.output_name.outputs.name }}
    steps:
      - run: echo "Apply"
      - id: output_name
        run: echo "name=hello_${{ github.actor }}_${{ inputs.input_name }}" >> $GITHUB_OUTPUT
